### PR TITLE
Fix eager tryGetSkikoRuntimeIfNeeded

### LINKED ISSUE #4886: [Gradle] tryGetSkikoRuntimeIfNeeded() eagerly resolves KMP runtime configuration on task creation
**Describe the bug**

We've got [following report](https://youtrack.jetbrains.com/issue/KT-68476) in Kotlin issues where `jvmRuntimeClasspath` configuration could not be further modified as it was already resolved:
```
Cannot change dependencies of dependency configuration ':micro_utils.android.pickers:jvmMainImplementation' after it has been included in dependency resolution.
```

The problem comes from both user repository and JB Compose Gradle plugin:
- user repository use Gradle `tasks.whenTaskAdded()` API [here](https://github.com/InsanusMokrassar/MicroUtils/blob/fa8a5bcd97d500c7c3d0ac40a7d00e7914559191/build.gradle#L35) which triggers eager tasks creation.
- The issue above triggers eager creation of Compose `AbstractConfigureDesktopPreviewTask` task which itself triggers `tryGetSkikoRuntimeIfNeeded()` method. Inside this method `previewClasspath` `FileCollection` [is resolved](https://github.com/JetBrains/compose-multiplatform/blob/7131b5b9a665e8b1d72aabc9476947650145c11e/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/preview/tasks/AbstractConfigureDesktopPreviewTask.kt#L89) which prevents further configuration modification (adding new dependencies)

**Affected platforms**
- All

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10
- Kotlin version:  2.0.0
- Gradle: 8.7

**To Reproduce**
1. Clone https://github.com/InsanusMokrassar/MicroUtils repository
2. Checkout `0.21.0` branch
3. Run `./gradlew :micro_utils.android.pickers:help -i -s`

**Expected behavior**

Configurations should not be resolved on Gradle configuration phase.

### PR DESCRIPTION
**Pull request by eymar**
Fixes #4886

## Testing
- Built the gradle plugin to mavenLocal
- used it in the reproducer of #4886, - the issue is gonve

This should be tested by QA

### Fixes - Gradle Plugin
- Make sure tryGetSkikoRuntimeIfNeeded is executed only during the task execution

### CODE REVIEW

File: gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/preview/tasks/AbstractConfigureDesktopPreviewTask.kt [hunk 1]
```diff
@@ -19,7 +19,7 @@ abstract class AbstractConfigureDesktopPreviewTask : AbstractComposeDesktopTask(
     internal lateinit var previewClasspath: FileCollection
 
     @get:InputFiles
-    internal lateinit var skikoRuntime: FileCollection
+    internal lateinit var skikoRuntime: Provider<FileCollection>
```
Comment (terrakok) [inline gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/preview/tasks/AbstractConfigureDesktopPreviewTask.kt:22]: internal abstract val skikoRuntime: Property<FileCollection>

Comment (eymar) [reply gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/preview/tasks/AbstractConfigureDesktopPreviewTask.kt]: done

**Review by terrakok — APPROVED** [review]
