### PR TITLE
Raise error when Homebrew JDK is used for packaging

### LINKED ISSUE #3107: Crash on macOS: Library not loaded libharfbuzz.0.dylib
**Describe the bug**
macOS application crashes during startup, stacktrace is below. Jar file works fine.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.7.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): macOS Monterey 12.6,1
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): OpenJDK >= 17

**To Reproduce**
1. Checkout repo https://github.com/aivanovski/autokpass.git
2. Creaete package for macOS: `./gradlew packageDmg`
3. Run the application

**Additional context**
Stacktrace
```
Exception in thread "TimerQueue" java.lang.UnsatisfiedLinkError: /Users/ivaali/Applications/autokpass-compose.app/Contents/runtime/Contents/Home/lib/libfontmanager.dylib: dlopen(/Users/ivaali/Applications/autokpass-compose.app/Contents/runtime/Contents/Home/lib/libfontmanager.dylib, 0x0001): Library not loaded: '/usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib'
  Referenced from: '/Users/ivaali/Applications/autokpass-compose.app/Contents/runtime/Contents/Home/lib/libfontmanager.dylib'
  Reason: tried: '/usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib' (no such file), '/usr/local/lib/libharfbuzz.0.dylib' (no such file), '/usr/lib/libharfbuzz.0.dylib' (no such file)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.base/java.lang.System.loadLibrary(Unknown Source)
        at java.desktop/sun.lwawt.macosx.LWCToolkit$1.run(Unknown Source)
        at java.desktop/sun.lwawt.macosx.LWCToolkit$1.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.desktop/sun.lwawt.macosx.LWCToolkit.<clinit>(Unknown Source)
        at java.desktop/sun.awt.PlatformGraphicsInfo.createToolkit(Unknown Source)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Unknown Source)
        at java.desktop/java.awt.Toolkit.getEventQueue(Unknown Source)
        at java.desktop/java.awt.EventQueue.invokeLater(Unknown Source)
        at java.desktop/javax.swing.SwingUtilities.invokeLater(Unknown Source)
        at java.desktop/javax.swing.Timer$1.run(Unknown Source)
        at java.desktop/javax.swing.Timer$1.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.desktop/javax.swing.Timer.post(Unknown Source)
        at java.desktop/javax.swing.TimerQueue.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class sun.lwawt.macosx.LWCToolkit
        at java.desktop/sun.awt.PlatformGraphicsInfo.createToolkit(Unknown Source)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Unknown Source)
        at java.desktop/javax.swing.UIManager.getSystemLookAndFeelClassName(Unknown Source)
        at org.jetbrains.skiko.Actuals_awtKt.setSystemLookAndFeel(Actuals.awt.kt:14)
        at org.jetbrains.skiko.Setup.init(Setup.kt:25)
        at org.jetbrains.skiko.Setup.init$default(Setup.kt:6)
        at org.jetbrains.skiko.Library.load(Library.kt:62)
        at org.jetbrains.skia.impl.Library$Companion.staticLoad(Library.jvm.kt:12)
        at androidx.compose.ui.ConfigureSwingGlobalsForCompose_desktopKt.configureSwingGlobalsForCompose(ConfigureSwingGlobalsForCompose.desktop.kt:49)
        at androidx.compose.ui.ConfigureSwingGlobalsForCompose_desktopKt.configureSwingGlobalsForCompose$default(ConfigureSwingGlobalsForCompose.desktop.kt:38)
        at androidx.compose.ui.window.Application_desktopKt.application(Application.desktop.kt:110)
        at androidx.compose.ui.window.Application_desktopKt.application$default(Application.desktop.kt:105)
        at com.github.ai.autokpass.MainKt.main(Main.kt:39)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /Users/ivaali/Applications/autokpass-compose.app/Contents/runtime/Contents/Home/lib/libfontmanager.dylib: dlopen(/Users/ivaali/Applications/autokpass-compose.app/Contents/runtime/Contents/Home/lib/libfontmanager.dylib, 0x0001): Library not loaded: '/usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib'
  Referenced from: '/Users/ivaali/Applications/autokpass-compose.app/Contents/runtime/Contents/Home/lib/libfontmanager.dylib'
  Reason: tried: '/usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib' (no such file), '/usr/local/lib/libharfbuzz.0.dylib' (no such file), '/usr/lib/libharfbuzz.0.dylib' (no such file) [in thread "TimerQueue"]
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.base/java.lang.System.loadLibrary(Unknown Source)
        at java.desktop/sun.lwawt.macosx.LWCToolkit$1.run(Unknown Source)
        at java.desktop/sun.lwawt.macosx.LWCToolkit$1.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.desktop/sun.lwawt.macosx.LWCToolkit.<clinit>(Unknown Source)
        at java.desktop/sun.awt.PlatformGraphicsInfo.createToolkit(Unknown Source)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Unknown Source)
        at java.desktop/java.awt.Toolkit.getEventQueue(Unknown Source)
        at java.desktop/java.awt.EventQueue.invokeLater(Unknown Source)
        at java.desktop/javax.swing.SwingUtilities.invokeLater(Unknown Source)
        at java.desktop/javax.swing.Timer$1.run(Unknown Source)
        at java.desktop/javax.swing.Timer$1.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.desktop/javax.swing.Timer.post(Unknown Source)
        at java.desktop/javax.swing.TimerQueue.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Failed to launch JVM
```

### PR DESCRIPTION
**Pull request by AlexeyTsvetkov**
Resolves #3107

### CODE REVIEW

File: gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/tasks/AbstractCheckNativeDistributionRuntime.kt [hunk 1]
```diff
@@ -69,18 +78,37 @@ abstract class AbstractCheckNativeDistributionRuntime : AbstractComposeDesktopTa
...
         ensureToolsExist(javaExecutable, jlinkExecutable, jpackageExecutabke)
 
-        val jvmRuntimeVersionString = getJavaRuntimeVersion(javaExecutable)
+        val jdkRuntimeProperties = getJDKRuntimeProperties(javaExecutable)
 
-        val jvmRuntimeVersion = jvmRuntimeVersionString?.toIntOrNull()
-            ?: jdkDistributionProbingError("JDK version '$jvmRuntimeVersionString' has unexpected format")
+        val jdkMajorVersionString = jdkRuntimeProperties.getProperty(JdkVersionProbe.JDK_MAJOR_VERSION_KEY)
+        val jdkMajorVersion = jdkMajorVersionString?.toIntOrNull()
+            ?: jdkDistributionProbingError("JDK version '$jdkMajorVersionString' has unexpected format")
```
Comment (dima-avdeev-jb) [inline gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/tasks/AbstractCheckNativeDistributionRuntime.kt:85]: Will JDK "1.8" parses correctly?
Or maybe because we don't support 1.8 it is no matter...

Comment (AlexeyTsvetkov) [reply gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/tasks/AbstractCheckNativeDistributionRuntime.kt:85]: The probe returns only major version, which is always an integer!

**Review by dima-avdeev-jb — APPROVED** [review]

**Comment by ellet0** [comment]
The JDK vendor check is using Java from the system path instead of the one specified for the Gradle task. I'm wondering if this is intentional or if there is a reason for this, developers might use different default Java versions for the System path, the configurations of the used JDK version will depend on the project
