### PR TITLE
Fix wix toolset download duplication

### LINKED ISSUE #3876: Duplicate destination file '...\.gradle\compose-jb\wix311.zip\wix311-binaries.zip'
**Describe the bug**
It is impossible to create a distributable file in a multi-module project.
Gradle show error: Duplicate destination file 'C:\Users\user1\.gradle\compose-jb\wix311.zip\wix311-binaries.zip'
I downloaded this archive myself, but it didn't help.
If you leave only one module in the project, the problem disappears.

**Affected platforms**
- Desktop (tested only it)

**Versions**
- Kotlin version*: from 1.8.20 to 1.9.10
- Compose Multiplatform version*: from 14.0 to 1.5.3
- OS version(s)* (required for Desktop and iOS issues):  Windows 10, macOS

Project:
https://github.com/denchic45/multi-module-compose-desktop

### PR DESCRIPTION
**Pull request by eymar**
Fixes #3876

### CODE REVIEW

File: gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/internal/wixToolset.kt [hunk 1]
```diff
@@ -39,12 +39,18 @@ internal fun JvmApplicationContext.configureWix() {
     val fileName = "wix311"
     val zipFile = wixDir.resolve("$fileName.zip")
     val unzipDir = root.layout.buildDirectory.dir(fileName)
-    val download = root.tasks.maybeCreate(DOWNLOAD_WIX_TOOLSET_TASK_NAME, Download::class.java).apply {
+    val download = root.tasks.findByName(DOWNLOAD_WIX_TOOLSET_TASK_NAME) ?: root.tasks.maybeCreate(
```
Comment (igordmn) [inline gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/internal/wixToolset.kt:42]: The `maybeCreate` suppose to return the task if it exists ([the source code](https://github.com/gradle/gradle/blob/8ec670c5eeddcdaba6ee840360cb4eeda788558e/subprojects/core/src/main/java/org/gradle/api/internal/AbstractNamedDomainObjectContainer.java#L60) calls `findByName`).

Does it definitely fixes the issue?

Comment (eymar) [reply gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/internal/wixToolset.kt:42]: yes, it fixes the issue.
The issue is casued by our `apply` block, which configures the task multiple times in our case, and each configuration adds a pair of `source` and `dest`. And apparently `dest` is supposed to be unique in Download task.

**Review by igordmn — APPROVED** [review]

**Review by pjBooms — APPROVED** [review]
